Repository grafana/k6, pull requests merged in 2021-03, with the labels that each got.

#1856 Add a way to mark http requests as failed or not(passed)
  core/engine.go
  core/local/local_test.go
  js/internal/modules/modules.go
  js/modules/k6/http/file_test.go
  js/modules/k6/http/http.go
  js/modules/k6/http/http_test.go
  js/modules/k6/http/request.go
  js/modules/k6/http/request_test.go
  js/modules/k6/http/response.go
  js/modules/k6/http/response_callback.go
  js/modules/k6/http/response_callback_test.go
  js/modules/k6/http/response_test.go
  js/runner.go
  lib/metrics/metrics.go
  lib/netext/httpext/request.go
  lib/netext/httpext/tracer.go
  lib/netext/httpext/transport.go
  lib/netext/httpext/transport_test.go
  stats/cloud/bench_test.go
  stats/cloud/cloud_easyjson.go
  stats/cloud/data.go
  stats/cloud/data_test.go
  stats/system_tag.go
  stats/system_tag_set_gen.go
  stats/units.go
Labels: documentation-needed

#1897 Drop the SSLv3 support
  js/bundle_test.go
  js/modules/k6/http/http.go
  lib/netext/tls.go
  lib/options_test.go
  lib/tlsconfig.go
Labels: breaking change

#1905 Split the cloud output so metric pushing is separate
  output/cloud/bench_test.go
  output/cloud/metrics_client.go
  output/cloud/output.go
  output/cloud/output_test.go
Labels: refactor

#1907 Don't always set the trail.Failed to true due to how SetValid works
  lib/netext/httpext/request_test.go
  lib/netext/httpext/transport.go
Labels: high prio
