Repository grafana/k6, pull requests merged in 2021-01, with the labels that each got.

#1785 Add go-header linter to check the license header
  .golangci.yml
  .license-template
Labels: ci

#1782 Update goja to latest master
  go.mod
  go.sum
  js/bundle.go
  js/lib/lib.go
  js/tc39/breaking_test_errors.json
  vendor/github.com/dop251/goja/README.md
  vendor/github.com/dop251/goja/ast/node.go
  vendor/github.com/dop251/goja/builtin_array.go
  vendor/github.com/dop251/goja/builtin_date.go
  vendor/github.com/dop251/goja/builtin_function.go
  vendor/github.com/dop251/goja/builtin_json.go
  vendor/github.com/dop251/goja/builtin_map.go
  vendor/github.com/dop251/goja/builtin_math.go
  vendor/github.com/dop251/goja/builtin_object.go
  vendor/github.com/dop251/goja/builtin_proxy.go
  vendor/github.com/dop251/goja/builtin_regexp.go
  vendor/github.com/dop251/goja/builtin_set.go
  vendor/github.com/dop251/goja/builtin_string.go
  vendor/github.com/dop251/goja/builtin_symbol.go
  vendor/github.com/dop251/goja/builtin_typedarrays.go
  vendor/github.com/dop251/goja/builtin_weakmap.go
  vendor/github.com/dop251/goja/builtin_weakset.go
  vendor/github.com/dop251/goja/compiler.go
  vendor/github.com/dop251/goja/file/file.go
  vendor/github.com/dop251/goja/func.go
  vendor/github.com/dop251/goja/object.go
  vendor/github.com/dop251/goja/object_lazy.go
  vendor/github.com/dop251/goja/parser/parser.go
  vendor/github.com/dop251/goja/parser/statement.go
  vendor/github.com/dop251/goja/proxy.go
  vendor/github.com/dop251/goja/regexp.go
  vendor/github.com/dop251/goja/runtime.go
  vendor/github.com/dop251/goja/srcfile.go
  vendor/github.com/dop251/goja/value.go
  vendor/github.com/dop251/goja/vm.go
  vendor/modules.txt
Labels: maintenance

#1794 Set Docker workdir to a writeable path
  Dockerfile
Labels: breaking change

#1768 Summary callback changes
  cmd/config.go
  cmd/options.go
  cmd/run.go
  js/common/util.go
  js/runner.go
  js/summary.go
  js/summary_test.go
  lib/consts/js.go
  lib/runner.go
  lib/testutils/minirunner/minirunner.go
  stats/sink.go
  stats/stats.go
  stats/stats_test.go
  ui/summary.go
  ui/summary_test.go
Labels: breaking change

#1795 Add/move SharedArray tests to it's module
  js/modules/k6/data/share_test.go
  js/share_test.go
Labels: lower prio, tests
