Repository grafana/k6, pull requests merged in 2021-12, with the labels that each got.

#2284 Prevent goroutines getting blocked in js tests
  js/console_test.go
  js/initcontext_test.go
  js/runner_test.go
Labels: tests

#2271 Make netext httpext Response's Request a pointer
  lib/netext/httpext/request.go
  lib/netext/httpext/response.go
Labels: enhancement

#2093 Add JS function to abort test
  cmd/run.go
  cmd/run_test.go
  cmd/testdata/abort.js
  cmd/testdata/abort_initerr.js
  cmd/testdata/abort_initvu.js
  cmd/testdata/abort_teardown.js
  cmd/testdata/initerr.js
  core/engine.go
  core/local/local.go
  errext/exitcodes/codes.go
  js/common/interrupt_error.go
  js/modules/k6/execution/execution.go
  js/modules/k6/execution/execution_test.go
  js/runner.go
  js/runner_test.go
  lib/execution.go
  lib/execution_status_gen.go
  lib/executor/helpers.go
Labels: documentation-needed
