Repository grafana/k6, pull requests merged in 2021-04, with the labels that each got.

#1943 Drop github.com/urfave/negroni as a dependency
  api/server.go
  api/server_test.go
  go.mod
  go.sum
  vendor/github.com/urfave/negroni/.gitignore
  vendor/github.com/urfave/negroni/CHANGELOG.md
  vendor/github.com/urfave/negroni/LICENSE
  vendor/github.com/urfave/negroni/README.md
  vendor/github.com/urfave/negroni/doc.go
  vendor/github.com/urfave/negroni/logger.go
  vendor/github.com/urfave/negroni/negroni.go
  vendor/github.com/urfave/negroni/recovery.go
  vendor/github.com/urfave/negroni/response_writer.go
  vendor/github.com/urfave/negroni/response_writer_pusher.go
  vendor/github.com/urfave/negroni/static.go
  vendor/modules.txt
Labels: maintenance, refactor

#1962 Call responseCallback with the emitted status code
  lib/netext/httpext/request_test.go
  lib/netext/httpext/transport.go
Labels: bug

#1963 Move statsd to output
  .golangci.yml
  cmd/outputs.go
  output/statsd/config.go
  output/statsd/datadog.go
  output/statsd/datadog_test.go
  output/statsd/output.go
  output/statsd/output_test.go
  output/statsd/test_helper.go
  stats/statsd/collector_test.go
  stats/statsd/common/api.go
  stats/statsd/common/collector.go
  stats/statsd/common/collector_test.go
Labels: refactor

#1982 Drop Collector interface and helpers
  cmd/outputs.go
  lib/run_status.go
Labels: lower prio, refactor

#1841 More ArrayBuffer support
  js/common/util.go
  js/common/util_test.go
  js/initcontext.go
  js/initcontext_test.go
  js/modules/k6/crypto/crypto.go
  js/modules/k6/crypto/crypto_test.go
  js/modules/k6/encoding/encoding.go
  js/modules/k6/encoding/encoding_test.go
  js/modules/k6/http/request.go
  js/modules/k6/http/request_test.go
  js/modules/k6/http/response.go
  js/modules/k6/ws/ws.go
  js/modules/k6/ws/ws_test.go
  lib/netext/httpext/batch.go
  lib/netext/httpext/compression.go
  lib/netext/httpext/response.go
Labels: breaking change
