Repository grafana/k6, pull requests merged in 2022-12, with the labels that each got.

#2786 xk6-websockets v0.1.6
  go.mod
  go.sum
  vendor/github.com/grafana/xk6-websockets/websockets/events/events.go
  vendor/github.com/grafana/xk6-websockets/websockets/helpers.go
  vendor/github.com/grafana/xk6-websockets/websockets/listeners.go
  vendor/github.com/grafana/xk6-websockets/websockets/params.go
  vendor/github.com/grafana/xk6-websockets/websockets/websockets.go
  vendor/modules.txt
Labels: documentation-needed

#2798 Wait for metrics handling to finish even when there is an error
  cmd/integration_test.go
  cmd/run.go
  core/engine.go
  core/local/local.go
Labels: bug

#2809 Remove dependency on the `js/` package (and goja) from `lib/*` packages
  js/modules/k6/grpc/client.go
  lib/netext/grpcext/conn.go
Labels: refactor

#2820 Fix link to protocols documentation in README.md
  README.md
Labels: docs
