Repository grafana/k6, pull requests merged in 2022-09, with the labels that each got.

#2605 Introduce a new flag to the k6 archive sub-command
  cmd/archive.go
  cmd/archive_test.go
Labels: enhancement

#2693 Dont lock the event loop once a promise rejection is left unhandled
  js/eventloop/eventloop.go
  js/runner_test.go
Labels: bug, high prio, js-compat

#2652 Detecting and filtering invalid environment names
  cmd/runtime_options.go
  cmd/runtime_options_test.go
  cmd/test_load.go
Labels: bug
