Repository grafana/k6, pull requests merged in 2022-04, with the labels that each got.

#2468 ui: fix all lint errors
  ui/form_fields.go
  ui/form_fields_test.go
  ui/form_test.go
  ui/pb/doc.go
  ui/pb/helpers_test.go
  ui/pb/progressbar_test.go
Labels: lower prio

#2469 Lint lib
  lib/archive.go
  lib/archive_test.go
  lib/execution_segment_test.go
  lib/executor/ramping_vus_test.go
  lib/fsext/changepathfs_test.go
  lib/fsext/trimpathseparator_test.go
  lib/fsext/walk.go
  lib/helpers.go
  lib/helpers_test.go
  lib/limiter.go
  lib/limiter_test.go
  lib/models_test.go
  lib/netext/dialer_test.go
  lib/netext/httpext/compression.go
  lib/netext/httpext/error_codes_syscall_posix.go
  lib/netext/httpext/tracer_test.go
  lib/netext/resolver_test.go
  lib/old_archive_test.go
  lib/options_test.go
  lib/testutils/httpmultibin/httpmultibin.go
  lib/types/ipblock_test.go
  lib/types/types_test.go
  lib/util.go
  lib/util_test.go
Labels: lower prio

#2467 Lint k6/html
  .golangci.yml
  js/modules/k6/html/element.go
  js/modules/k6/html/element_test.go
  js/modules/k6/html/elements.go
  js/modules/k6/html/elements_gen.go
  js/modules/k6/html/elements_gen_test.go
  js/modules/k6/html/gen/gen_elements.go
  js/modules/k6/html/html.go
  js/modules/k6/html/serialize.go
  js/modules/k6/html/util.go
Labels: lower prio

#2375 js/console: Marshal by default native JS objects
  js/console.go
  js/console_test.go
Labels: breaking change

#2463 Validate thresholds at init
  cmd/archive_test.go
  cmd/run_test.go
  cmd/test_load.go
  cmd/testdata/thresholds/non_existing_metric.js
  cmd/testdata/thresholds/unsupported_aggregation_method.js
  metrics/metric.go
  metrics/metric_test.go
  metrics/metric_type.go
  metrics/thresholds.go
  metrics/thresholds_parser.go
  metrics/thresholds_parser_test.go
  metrics/thresholds_test.go
Labels: feature

#2437 chore: update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: docs
