Repository grafana/k6, pull requests merged in 2022-11, with the labels that each got.

#2712 Return HTTP response to user for failed connections.
  js/modules/k6/ws/ws.go
  js/modules/k6/ws/ws_test.go
Labels: breaking change

#2759 Fix 2755 and ensure evaulation of thresholds over trend metrics median
  js/summary.go
  metrics/sample.go
  metrics/sink.go
  metrics/sink_test.go
  metrics/thresholds.go
  metrics/thresholds_test.go
Labels: bug, high prio

#2771 Disable containedctx
  .golangci.yml
Labels: maintenance
