Repository grafana/k6, pull requests merged in 2022-10, with the labels that each got.

#2707 Update goja
  go.mod
  go.sum
  vendor/github.com/dop251/goja/builtin_function.go
  vendor/github.com/dop251/goja/func.go
  vendor/github.com/dop251/goja/object_goarray_reflect.go
  vendor/github.com/dop251/goja/object_gomap_reflect.go
  vendor/github.com/dop251/goja/object_goreflect.go
  vendor/github.com/dop251/goja/object_goslice_reflect.go
  vendor/github.com/dop251/goja/parser/lexer.go
  vendor/github.com/dop251/goja/runtime.go
  vendor/github.com/dop251/goja/value.go
  vendor/github.com/dop251/goja/vm.go
  vendor/modules.txt
Labels: maintenance

#2710 Update goja - incorrect handling of continue in for-in
  go.mod
  go.sum
  vendor/github.com/dop251/goja/compiler_stmt.go
  vendor/modules.txt
Labels: maintenance

#2702 k6/net/grpc: initialize grpc from a protoset
  js/modules/k6/grpc/client.go
  js/modules/k6/grpc/client_test.go
  lib/testutils/httpmultibin/grpc_protoset_testing/test.protoset
  lib/testutils/httpmultibin/grpc_protoset_testing/test_message.proto
  lib/testutils/httpmultibin/grpc_protoset_testing/test_service.proto
Labels: documentation-needed

#2739 Make common.Throw add stacktraces the same as returning an error
  js/common/util.go
  js/common/util_test.go
  js/eventloop/eventloop_test.go
  js/modules/k6/http/file_test.go
Labels: evaluation needed

#2741 Fix flaky CSV output test
  output/csv/output_test.go
Labels: tests
