Repository grafana/k6, pull requests merged in 2022-06, with the labels that each got.

#2534 Make html.Selection.map return []goja.Value instead of []string
  js/modules/k6/html/html.go
  js/modules/k6/html/html_test.go
Labels: bug

#2561 Add tests covering v0.38.* thresholds regressions
  cmd/run_test.go
  cmd/testdata/thresholds/empty_sink_no_nan.js
  cmd/testdata/thresholds/name_contains_tokens.js
  cmd/testdata/thresholds/thresholds_on_submetric_without_samples.js
Labels: enhancement

#2532 Try to respect zero target stages at the end
  lib/executor/ramping_vus.go
  lib/executor/ramping_vus_test.go
Labels: evaluation needed
