Repository grafana/k6, pull requests merged in 2022-01, with the labels that each got.

#2314 fix: Implementing a limitation for the open()
  js/bundle.go
  js/initcontext.go
  js/runner_test.go
  lib/archive.go
  lib/fsext/cacheonread.go
  loader/readsource.go
Labels: breaking change, documentation-needed

#2251 Fix/1443 remove the JS runtime from threshold calculations
  core/engine_test.go
  stats/thresholds.go
  stats/thresholds_parser.go
  stats/thresholds_parser_test.go
  stats/thresholds_test.go
Labels: enhancement

#2335 Revert "Merge pull request #2251 from grafana/fix/1443_remove_the_js_…
  core/engine_test.go
  stats/thresholds.go
  stats/thresholds_parser.go
  stats/thresholds_parser_test.go
  stats/thresholds_test.go
Labels: bug

#2331 Fix all linter errors in loader package
  loader/cdnjs_test.go
  loader/github_test.go
  loader/loader.go
  loader/loader_test.go
  loader/readsource_test.go
Labels: refactor

#2341 HTML package linter fixes
  js/modules/k6/html/element.go
  js/modules/k6/html/element_test.go
  js/modules/k6/html/elements.go
  js/modules/k6/html/elements_gen_test.go
  js/modules/k6/html/elements_test.go
  js/modules/k6/html/html_test.go
  js/modules/k6/html/serialize_test.go
Labels: refactor

#2337 Use envconfig fork to abstract os package
  cloudapi/api_test.go
  cloudapi/config.go
  cloudapi/config_test.go
  cmd/archive.go
  cmd/cloud.go
  cmd/config.go
  cmd/config_consolidation_test.go
  cmd/config_test.go
  cmd/inspect.go
  cmd/run.go
  go.mod
  go.sum
  lib/options_test.go
  lib/testutils/env.go
  output/csv/config.go
  output/influxdb/config.go
  output/statsd/config.go
  vendor/github.com/mstoykov/envconfig/LICENSE
  vendor/github.com/mstoykov/envconfig/MAINTAINERS
  vendor/github.com/mstoykov/envconfig/README.md
  vendor/github.com/mstoykov/envconfig/doc.go
  vendor/github.com/mstoykov/envconfig/env_os.go
  vendor/github.com/mstoykov/envconfig/env_syscall.go
  vendor/github.com/mstoykov/envconfig/envconfig.go
  vendor/github.com/mstoykov/envconfig/usage.go
  vendor/modules.txt
Labels: refactor

#2336 cmd/convert refactor to not use global variables
  cmd/common.go
  cmd/convert.go
  cmd/convert_test.go
  cmd/root.go
Labels: refactor

#2358 Remove global logrus usage from DeriveScenariosFromShortcuts
  cmd/archive.go
  cmd/cloud.go
  cmd/config.go
  cmd/config_consolidation_test.go
  cmd/config_test.go
  cmd/inspect.go
  cmd/run.go
  core/engine_test.go
  core/local/local_test.go
  lib/executor/execution_config_shortcuts.go
Labels: refactor

#2353 Cmd no globals
  cmd/archive.go
  cmd/cloud.go
  cmd/common.go
  cmd/config.go
  cmd/config_consolidation_test.go
  cmd/inspect.go
  cmd/login_cloud.go
  cmd/login_influxdb.go
  cmd/outputs.go
  cmd/pause.go
  cmd/resume.go
  cmd/root.go
  cmd/run.go
  cmd/run_test.go
  cmd/scale.go
  cmd/stats.go
  cmd/status.go
  cmd/ui.go
  cmd/ui_test.go
Labels: refactor

#2357 Don't use global variables to initialize test cases
  cmd/runtime_options_test.go
Labels: refactor
