Repository grafana/k6, pull requests merged in 2022-05, with the labels that each got.

#2513 Fix v0.38.0 release notes
  release notes/v0.38.0.md
Labels: docs

#2521 Fix threshold over rate metric resulting in `NaN` result
  core/engine.go
  core/engine_test.go
  metrics/engine/engine.go
  metrics/sink.go
  metrics/thresholds.go
  metrics/thresholds_test.go
Labels: bug

#2524 Update goja to from 9037c2b to 4418d45
  go.mod
  go.sum
  js/compiler/compiler.go
  js/compiler/compiler_test.go
  js/tc39/breaking_test_errors.json
  vendor/github.com/dop251/goja/builtin_array.go
  vendor/github.com/dop251/goja/builtin_math.go
  vendor/github.com/dop251/goja/builtin_string.go
  vendor/github.com/dop251/goja/builtin_typedarrays.go
  vendor/github.com/dop251/goja/compiler_expr.go
  vendor/github.com/dop251/goja/parser/expression.go
  vendor/github.com/dop251/goja/parser/lexer.go
  vendor/github.com/dop251/goja/runtime.go
  vendor/github.com/dop251/goja/token/token_const.go
  vendor/github.com/dop251/goja/vm.go
  vendor/modules.txt
Labels: dependencies

#2542 Ensure rate sinks with no samples are formatted as 0%
  metrics/sink.go
Labels: bug
