Repository grafana/k6, pull requests merged in 2022-03, with the labels that each got.

#2441 Update `dop251/goja` from `cfb079c` to `b09a6bf`
  go.mod
  go.sum
  vendor/github.com/dop251/goja/compiler.go
  vendor/github.com/dop251/goja/compiler_expr.go
  vendor/github.com/dop251/goja/compiler_stmt.go
  vendor/github.com/dop251/goja/vm.go
  vendor/modules.txt
Labels: maintenance, dependencies

#2410 Remove most direct access to the `os` package, support `NO_COLOR` and `K6_NO_COLOR`
  cmd/archive.go
  cmd/archive_test.go
  cmd/cloud.go
  cmd/common.go
  cmd/config.go
  cmd/config_consolidation_test.go
  cmd/convert.go
  cmd/convert_test.go
  cmd/inspect.go
  cmd/login_cloud.go
  cmd/login_influxdb.go
  cmd/outputs.go
  cmd/pause.go
  cmd/resume.go
  cmd/root.go
  cmd/root_test.go
  cmd/run.go
  cmd/run_test.go
  cmd/runtime_options.go
  cmd/scale.go
  cmd/stats.go
  cmd/status.go
  cmd/ui.go
  cmd/ui_test.go
  cmd/version.go
  lib/testutils/logrus_hook.go
  loader/filesystems.go
  log/file.go
  log/file_test.go
Labels: breaking change

#2446 Maintenance update of github.com/spf13/cobra to v1.4.0 from v1.1.3
  Dependencies.md
  go.mod
  go.sum
  modtools_frozen.yml
  vendor/github.com/spf13/cobra/MAINTAINERS
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/bash_completionsV2.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/command_notwin.go
  vendor/github.com/spf13/cobra/command_win.go
  vendor/github.com/spf13/cobra/completions.go
  vendor/github.com/spf13/cobra/fish_completions.go
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/github.com/spf13/cobra/projects_using_cobra.md
  vendor/github.com/spf13/cobra/shell_completions.md
  vendor/github.com/spf13/cobra/user_guide.md
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/modules.txt
Labels: maintenance, dependencies

#2442 Remove `stats.New`
  api/v1/metric_routes_test.go
  api/v1/metric_test.go
  core/local/local_test.go
  js/summary_test.go
  metrics/registry.go
  output/csv/output_test.go
  output/helpers_test.go
  output/influxdb/bench_test.go
  output/influxdb/output_test.go
  output/json/json_test.go
  output/statsd/test_helper.go
  stats/stats.go
  stats/stats_test.go
Labels: refactor
