Repository grafana/k6, pull requests merged in 2023-07, with the labels that each got.

#3158 output/cloudv2: Return empty string instead of "unknown" in rmCollector
  output/cloud/expv2/collect.go
  output/cloud/expv2/collect_test.go
Labels: bug

#3157 Introducing the MaxTimeSeriesInBatch config option
  cloudapi/config.go
  cloudapi/config_test.go
  output/cloud/expv2/flush.go
  output/cloud/expv2/flush_test.go
  output/cloud/expv2/output.go
  output/cloud/output.go
Labels: cloud

#3163 Fix examples/grpc.js
  examples/grpc.js
Labels: docs, area: grpc

#3162 feat: catch, discard & warn about the labels that have reserved names
  output/cloud/expv2/flush.go
  output/cloud/expv2/flush_test.go
  output/cloud/expv2/mapping.go
  output/cloud/expv2/output.go
Labels: cloud

#3178 fix for registering nested message types
  js/modules/k6/grpc/client.go
  js/modules/k6/grpc/client_test.go
  lib/testutils/httpmultibin/grpc_testing/nested_types.proto
Labels: area: grpc

#3150 output/cloudv2: Add retry support to insights client
  cloudapi/config.go
  cloudapi/config_test.go
  cloudapi/insights/client.go
  cloudapi/insights/client_test.go
  go.mod
  go.sum
  output/cloud/expv2/flush.go
  output/cloud/expv2/flush_test.go
  output/cloud/expv2/output.go
  output/cloud/expv2/output_test.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/LICENSE
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/retry/backoff.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/retry/doc.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/retry/options.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/retry/retry.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/util/backoffutils/backoff.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/util/metautils/doc.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/util/metautils/nicemd.go
  vendor/modules.txt
Labels: feature

#3176 Add a `promises` package with a `New` helper function
  js/promises/promises.go
Labels: enhancement

#3169 output/cloudv2: Compact histogram
  output/cloud/expv2/hdr.go
  output/cloud/expv2/hdr_test.go
  output/cloud/expv2/integration/testdata/metricset.json
  output/cloud/expv2/pbcloud/metric.pb.go
  output/cloud/expv2/pbcloud/metric.proto
  output/cloud/expv2/sink.go
  output/cloud/expv2/sink_test.go
Labels: cloud

#3180 Address eventloop's double registerCallback call when using promises.New
  js/promises/promises.go
  js/promises/promises_test.go
Labels: bug

#3184 output/cloudv2: Fix insights client initialization
  output/cloud/expv2/output.go
Labels: bug, high prio

#3181 Add a `RunOnEventLoop` method to `modulestest.Runtime`
  js/modules/k6/experimental/tracing/client_test.go
  js/modules/k6/http/async_request_test.go
  js/modules/k6/http/response_callback_test.go
  js/modules/k6/k6_test.go
  js/modulestest/runtime.go
Labels: enhancement

#3130 chore: remove refs to deprecated io/ioutil
  cmd/archive_test.go
  cmd/convert_test.go
  cmd/run_test.go
  examples/grpc_server/main.go
  js/bundle_test.go
  js/console_test.go
  js/runner_test.go
  ui/pb/progressbar_test.go
Labels: maintenance

#3195 cloudv2: Make sure to use the overwritten config
  output/cloud/expv2/output.go
  output/cloud/expv2/output_test.go
  output/cloud/output.go
Labels: cloud

#3202 k6 Insights (2/2): Integrate request metadata output to cloud output v1
  cloudapi/insights/client.go
  cloudapi/insights/client_test.go
  output/cloud/expv2/output.go
  output/cloud/v1/output.go
Labels: feature, high prio

#3206 Implement concurrent pushes across batches
  output/cloud/expv2/flush.go
  output/cloud/expv2/flush_test.go
  output/cloud/expv2/output.go
  output/cloud/expv2/output_test.go
Labels: high prio

#3231 Fix tracing module sampling option should default to 1.0 when not set
  cmd/tests/tracing_module_test.go
  js/modules/k6/experimental/tracing/module.go
  js/modules/k6/experimental/tracing/options.go
Labels: bug
