Repository grafana/k6, pull requests merged in 2023-02, with the labels that each got.

#2903 js: Cache scripts by absolute not relative paths
  js/initcontext.go
  js/initcontext_test.go
Labels: high prio, breaking change

#2906 Csv time formats
  output/csv/config.go
  output/csv/output.go
  output/csv/output_test.go
  output/csv/time_format_gen.go
Labels: documentation-needed

#2938 Fix usage report block of k6 execution if it takes longer than 3s
  cmd/run.go
Labels: high prio
