Repository grafana/k6, pull requests merged in 2023-06, with the labels that each got.

#3111 Update to v0.10.0 of xk6-browser
  go.mod
  go.sum
  vendor/github.com/grafana/xk6-browser/common/frame.go
  vendor/github.com/grafana/xk6-browser/common/frame_session.go
  vendor/github.com/grafana/xk6-browser/common/js/injected_script.js
  vendor/github.com/grafana/xk6-browser/common/locator.go
  vendor/github.com/grafana/xk6-browser/common/remote_object.go
  vendor/github.com/grafana/xk6-browser/k6ext/metrics.go
  vendor/modules.txt
Labels: dependencies

#3100 output/cloudv2: Implement RequestMetadata output
  cloudapi/config.go
  cloudapi/config_test.go
  cloudapi/insights/client.go
  cloudapi/insights/client_test.go
  cloudapi/insights/doc.go
  cloudapi/insights/domain.go
  cloudapi/insights/mappers.go
  cloudapi/insights/mappers_test.go
  cloudapi/insights/proto/gen.go
  cloudapi/insights/proto/v1/common/common.pb.go
  cloudapi/insights/proto/v1/common/common.proto
  cloudapi/insights/proto/v1/ingester/ingester.pb.go
  cloudapi/insights/proto/v1/ingester/ingester.proto
  cloudapi/insights/proto/v1/ingester/ingester_grpc.pb.go
  cloudapi/insights/proto/v1/k6/labels.pb.go
  cloudapi/insights/proto/v1/k6/labels.proto
  cloudapi/insights/proto/v1/k6/request_metadata.pb.go
  cloudapi/insights/proto/v1/k6/request_metadata.proto
  cloudapi/insights/proto/v1/trace/labels.pb.go
  cloudapi/insights/proto/v1/trace/labels.proto
  cloudapi/insights/proto/v1/trace/span.pb.go
  cloudapi/insights/proto/v1/trace/span.proto
  output/cloud/expv2/collect.go
  output/cloud/expv2/collect_test.go
  output/cloud/expv2/flush.go
  output/cloud/expv2/flush_test.go
  output/cloud/expv2/output.go
  vendor/google.golang.org/grpc/test/bufconn/bufconn.go
  vendor/modules.txt
Labels: feature

#3101 Add File API proposal design document
  docs/design/019-file-api.md
Labels: enhancement, ux, feature

#3146 TestOutputFlush always enabled
  output/cloud/expv2/integration/integration_test.go
Labels: tests, cloud, lower prio

#3151 chore: fix typo
  .github/pull_request_template.md
Labels: docs, lower prio
