Repository grafana/k6, pull requests merged in 2023-08, with the labels that each got.

#3251 Fix tracing module's Jaeger sampling flag
  js/modules/k6/experimental/tracing/propagator.go
  js/modules/k6/experimental/tracing/propagator_test.go
Labels: bug

#3246 Release notes v0.46.0
  release notes/v0.46.0.md
Labels: documentation-needed

#3279 ci: fix issue SBOM not being triggered 🐛
  .github/workflows/build.yml
  .github/workflows/sbom-report.yml
Labels: ci

#3288 Deprecate prepending https:// in tries to load modules
  loader/loader.go
Labels: breaking change

#3289 tc39: Don't run some unicode tests as they are flaky between go versions
  js/tc39/breaking_test_errors.json
  js/tc39/tc39_test.go
Labels: ci

#3234 Support binary passed in GRPC metadata
  js/modules/k6/grpc/client.go
  js/modules/k6/grpc/client_test.go
Labels: documentation-needed, area: grpc
