Repository grafana/k6, pull requests merged in 2023-11, with the labels that each got.

#3420 Address potential races in `fs.read` and `fs.seek` operations
  js/modules/k6/experimental/fs/file.go
  js/modules/k6/experimental/fs/file_test.go
  js/modules/k6/experimental/fs/module.go
  js/modules/k6/experimental/fs/module_test.go
Labels: bug, enhancement

#3437 Set `K6_CLOUD_TRACES_HOST` to new hostname
  cloudapi/config.go
Labels: cloud

#3429 fix TestSetupTimeout by increasing the time range it should finish in
  cmd/tests/cmd_run_test.go
Labels: ci

#3394 Add k6 new subcommand
  .gitignore
  cmd/new.go
  cmd/new_test.go
  cmd/root.go
Labels: documentation-needed

#3438 fix EOF errors on http response with content and encoding headers
  js/modules/k6/http/request_test.go
  lib/netext/httpext/compression.go
Labels: bug

#3443 Golang versions convention
  Dependencies.md
Labels: docs

#3370 Expose profiling endpoints
  api/server.go
  cmd/root.go
  cmd/run.go
  cmd/state/state.go
  cmd/ui.go
Labels: documentation-needed

#3442 Add support for --version flag
  cmd/root.go
  cmd/tests/cmd_run_test.go
  cmd/version.go
Labels: ux, documentation-needed

#3446 Move log tokenizer to `lib/strvals` package
  lib/strvals/doc.go
  lib/strvals/parser.go
  lib/strvals/parser_test.go
  log/file.go
  log/loki.go
Labels: refactor

#3452 Add fsext.Abs helper function
  js/initcontext.go
  lib/fsext/filepath.go
  lib/fsext/filepath_unix_test.go
  lib/fsext/filepath_windows_test.go
Labels: enhancement

#3451 breaking change: Don't try to prepend https to module specifiers
  js/tc39/breaking_test_errors.json
  js/tc39/tc39_test.go
  lib/old_archive_test.go
  loader/loader.go
  loader/loader_test.go
  loader/readsource.go
Labels: breaking change

#3165 [fs] Expose an experimental `fs` module with an `open` function and a `File` abstraction (1/3)
  examples/experimental/fs/bonjour.txt
  examples/experimental/fs/fs.js
  js/jsmodules.go
  js/modules/k6/experimental/fs/cache.go
  js/modules/k6/experimental/fs/cache_test.go
  js/modules/k6/experimental/fs/errors.go
  js/modules/k6/experimental/fs/errors_gen.go
  js/modules/k6/experimental/fs/file.go
  js/modules/k6/experimental/fs/file_test.go
  js/modules/k6/experimental/fs/module.go
  js/modules/k6/experimental/fs/module_test.go
Labels: enhancement, feature, documentation-needed

#3448 metrics: enforce more otel/prometheus aligned names
  cmd/tests/cmd_run_test.go
  js/bundle.go
  metrics/registry.go
  metrics/registry_test.go
Labels: breaking change, documentation-needed

#3389 Remove the --logformat flag
  cmd/root.go
  cmd/root_test.go
Labels: breaking change

#3469 Bump golangci-lint to v1.55.2
  .golangci.yml
Labels: ci, maintenance
