Repository grafana/k6, pull requests merged in 2023-05, with the labels that each got.

#3070 Update xk6-output-prometheus-remote to v0.2.1
  go.mod
  go.sum
  vendor/modules.txt
Labels: maintenance

#3095 .golangci.yml maintenance
  .golangci.yml
Labels: lower prio, maintenance

#2963 output/cloudv2: Binary-based payload
  cloudapi/client.go
  output/cloud/expv2/metrics_client.go
  output/cloud/expv2/metrics_client_test.go
  output/cloud/expv2/pbcloud/gen.go
  output/cloud/expv2/pbcloud/metric.pb.go
  output/cloud/expv2/pbcloud/metric.proto
  vendor/github.com/klauspost/compress/s2/.gitignore
  vendor/github.com/klauspost/compress/s2/LICENSE
  vendor/github.com/klauspost/compress/s2/README.md
  vendor/github.com/klauspost/compress/s2/decode.go
  vendor/github.com/klauspost/compress/s2/decode_amd64.s
  vendor/github.com/klauspost/compress/s2/decode_arm64.s
  vendor/github.com/klauspost/compress/s2/decode_asm.go
  vendor/github.com/klauspost/compress/s2/decode_other.go
  vendor/github.com/klauspost/compress/s2/dict.go
  vendor/github.com/klauspost/compress/s2/encode.go
  vendor/github.com/klauspost/compress/s2/encode_all.go
  vendor/github.com/klauspost/compress/s2/encode_amd64.go
  vendor/github.com/klauspost/compress/s2/encode_best.go
  vendor/github.com/klauspost/compress/s2/encode_better.go
  vendor/github.com/klauspost/compress/s2/encode_go.go
  vendor/github.com/klauspost/compress/s2/encodeblock_amd64.go
  vendor/github.com/klauspost/compress/s2/encodeblock_amd64.s
  vendor/github.com/klauspost/compress/s2/index.go
  vendor/github.com/klauspost/compress/s2/lz4convert.go
  vendor/github.com/klauspost/compress/s2/lz4sconvert.go
  vendor/github.com/klauspost/compress/s2/reader.go
  vendor/github.com/klauspost/compress/s2/s2.go
  vendor/github.com/klauspost/compress/s2/writer.go
  vendor/github.com/klauspost/compress/snappy/.gitignore
  vendor/github.com/klauspost/compress/snappy/AUTHORS
  vendor/github.com/klauspost/compress/snappy/CONTRIBUTORS
  vendor/github.com/klauspost/compress/snappy/LICENSE
  vendor/github.com/klauspost/compress/snappy/README.md
  vendor/github.com/klauspost/compress/snappy/decode.go
  vendor/github.com/klauspost/compress/snappy/encode.go
  vendor/github.com/klauspost/compress/snappy/snappy.go
  vendor/modules.txt
Labels: cloud
