Repository grafana/k6, pull requests merged in 2023-12, with the labels that each got.

#3491 Pin golang version to 1.21.5 in github actions and docker
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/tc39.yml
  .github/workflows/test.yml
  .github/workflows/xk6.yml
  Dockerfile
Labels: ci

#3485 Fix lint issues in api package
  api/server.go
  api/server_test.go
Labels: bug, maintenance

#3478 Fix lint issues in js/compiler
  js/compiler/compiler.go
Labels: maintenance

#3483 Fix lint issues in output/cloud/*
  output/cloud/output.go
  output/cloud/output_test.go
  output/cloud/v1/data.go
  output/cloud/v1/output.go
  output/cloud/v1/output_test.go
Labels: maintenance

#3440 Add built-in root certificate fallbacks
  Dockerfile
  cmd/common.go
  go.mod
  go.sum
  vendor/golang.org/x/crypto/x509roots/fallback/LICENSE
  vendor/golang.org/x/crypto/x509roots/fallback/bundle.go
  vendor/golang.org/x/crypto/x509roots/fallback/fallback.go
  vendor/modules.txt
Labels: enhancement

#3473 Release process recent changes
  .github/ISSUE_TEMPLATE/release.md
Labels: docs

#3496 Adds trivy scheduled checks
  .github/workflows/trivy.yml
Labels: ci

#3501 Update to xk6-timers v0.2.2 - fixing ordering of timers
  go.mod
  go.sum
  vendor/github.com/grafana/xk6-timers/timers/timers.go
  vendor/modules.txt
Labels: dependencies

#3489 Assign pull-requests via CODEOWNERS
  .github/workflows/pr-auto-assign.yml
  CODEOWNERS
Labels: lower prio, ci, maintenance
