Repository grafana/k6, pull requests merged in 2023-10, with the labels that each got.

#3378 Gh fixes
  .github/workflows/build.yml
Labels: ci

#3388 grcp-demo-service: Update the transitive dependencies
  examples/grpc_server/go.mod
  examples/grpc_server/go.sum
Labels: dependencies

#3380 fix: Set console log level to the application one when writing to file
  js/console.go
  js/runner.go
Labels: bug

#3393 Fix js lint
  js/bundle.go
  js/bundle_test.go
  js/console.go
  js/console_test.go
  js/empty_iterations_bench_test.go
  js/http_bench_test.go
  js/initcontext_test.go
  js/module_loading_test.go
  js/runner.go
  js/runner_test.go
  js/summary.go
Labels: refactor

#3390 output/csv: Remove the support for snake_case options
  output/csv/config.go
  output/csv/config_test.go
Labels: breaking change

#3397 Update goja
  go.mod
  go.sum
  vendor/github.com/dop251/goja/builtin_json.go
  vendor/github.com/dop251/goja/compiler.go
  vendor/github.com/dop251/goja/runtime.go
  vendor/modules.txt
Labels: dependencies

#3398 Set `K6_CLOUD_TRACES_ENABLED` to `true` by default
  cloudapi/config.go
Labels: cloud

#3421 Update xk6 integration tests dependancy
  .github/workflows/xk6-tests/xk6-js-test/go.mod
  .github/workflows/xk6-tests/xk6-js-test/go.sum
  .github/workflows/xk6-tests/xk6-output-test/go.mod
  .github/workflows/xk6-tests/xk6-output-test/go.sum
Labels: high prio, ci

#3425 Add k6 browser hot fix for networking deadlock
  go.mod
  go.sum
  vendor/github.com/grafana/xk6-browser/common/network_manager.go
  vendor/modules.txt
Labels: bug, area: browser

#3423 Adds the K6_INFLUXDB_PROXY environment variable support, closes #3418
  output/influxdb/config.go
  output/influxdb/config_test.go
  output/influxdb/util.go
Labels: hacktoberfest, documentation-needed
