Repository grafana/k6, pull requests merged in 2023-01, with the labels that each got.

#2800 Pass and respect a `Context` when initializing VUs
  cmd/integration_test.go
  core/local/local.go
  js/bundle.go
  js/bundle_test.go
  js/console_test.go
  js/empty_iterations_bench_test.go
  js/http_bench_test.go
  js/init_and_modules_test.go
  js/initcontext.go
  js/initcontext_test.go
  js/module_loading_test.go
  js/modules/k6/marshalling_test.go
  js/path_resolution_test.go
  js/runner.go
  js/runner_test.go
  js/share_test.go
  lib/executor/common_test.go
  lib/executor/ramping_arrival_rate_test.go
  lib/executor/vu_handle_test.go
  lib/runner.go
  lib/testutils/minirunner/minirunner.go
Labels: bug, tests

#2803 Ensure REST API server is shut down after test ends and check for goroutine leaks
  api/server.go
  cmd/root_test.go
  cmd/run.go
  go.mod
  go.sum
  vendor/go.uber.org/goleak/.gitignore
  vendor/go.uber.org/goleak/CHANGELOG.md
  vendor/go.uber.org/goleak/LICENSE
  vendor/go.uber.org/goleak/README.md
  vendor/go.uber.org/goleak/doc.go
  vendor/go.uber.org/goleak/internal/stack/stacks.go
  vendor/go.uber.org/goleak/leaks.go
  vendor/go.uber.org/goleak/options.go
  vendor/go.uber.org/goleak/testmain.go
  vendor/go.uber.org/goleak/tracestack_new.go
  vendor/modules.txt
Labels: bug, tests, refactor

#2807 Use non-zero exit codes for some aborted by Ctrl+C or REST API tests
  api/v1/group_routes_test.go
  api/v1/status_routes_test.go
  cmd/integration_test.go
  cmd/run.go
  core/engine.go
  core/engine_test.go
  errext/exitcodes/codes.go
Labels: ux, breaking change

#2835 Update template for release notes
  release notes/template.md
Labels: docs

#2810 Add new `errext.AbortReason` type, move and use old `RunStatus` type only for k6 cloud code
  api/v1/setup_teardown_routes_test.go
  api/v1/status_routes_test.go
  cloudapi/api.go
  cloudapi/run_status.go
  cmd/cloud.go
  cmd/run.go
  cmd/tests/cmd_cloud_test.go
  cmd/tests/cmd_run_test.go
  core/engine.go
  core/engine_test.go
  errext/abort_reason.go
  errext/exception.go
  errext/interrupt_error.go
  js/runner.go
  js/runner_test.go
  js/timeout_error.go
  lib/testutils/mockoutput/mockoutput.go
  output/cloud/output.go
  output/cloud/output_test.go
  output/manager.go
  output/types.go
Labels: refactor

#2812 Move `core/local/ExecutionScheduler` to `execution/Scheduler`
  api/server_test.go
  api/v1/group_routes_test.go
  api/v1/metric_routes_test.go
  api/v1/setup_teardown_routes_test.go
  api/v1/status_routes.go
  api/v1/status_routes_test.go
  cmd/run.go
  core/engine.go
  core/engine_test.go
  core/local/util_test.go
  execution/abort.go
  execution/pkg.go
  execution/scheduler.go
  execution/scheduler_ext_exec_test.go
  execution/scheduler_ext_test.go
  execution/scheduler_int_test.go
  js/runner_test.go
  lib/execution.go
  lib/executor/helpers.go
Labels: refactor

#2855 Experimental tracing module (3/3): define and expose a `instrumentHTTP` function
  cmd/tests/tracing_module_test.go
  js/modules/k6/experimental/tracing/module.go
  js/modules/k6/experimental/tracing/module_test.go
  samples/experimental/tracing/tracing-instrumentHTTP.js
Labels: feature, high prio

#2854 Experimental tracing module (2/3): define and expose a `tracing.Client`
  cmd/tests/tracing_module_test.go
  js/modules/k6/experimental/tracing/client.go
  js/modules/k6/experimental/tracing/client_test.go
  js/modules/k6/experimental/tracing/goja.go
  js/modules/k6/experimental/tracing/module.go
  js/modules/k6/experimental/tracing/module_test.go
  js/modules/k6/experimental/tracing/options.go
  js/modules/k6/experimental/tracing/options_test.go
  js/modules/k6/experimental/tracing/trace_id.go
  samples/experimental/tracing-client.js
  samples/experimental/tracing/tracing-instrumentHTTP.js
Labels: feature, high prio

#2853 Experimental tracing module (1/3): implement trace ids generation and propagation
  cmd/tests/tracing_module_test.go
  js/jsmodules.go
  js/modules/k6/experimental/tracing/client.go
  js/modules/k6/experimental/tracing/client_test.go
  js/modules/k6/experimental/tracing/encoding.go
  js/modules/k6/experimental/tracing/goja.go
  js/modules/k6/experimental/tracing/module.go
  js/modules/k6/experimental/tracing/module_test.go
  js/modules/k6/experimental/tracing/options.go
  js/modules/k6/experimental/tracing/options_test.go
  js/modules/k6/experimental/tracing/propagator.go
  js/modules/k6/experimental/tracing/trace_id.go
  js/modules/k6/experimental/tracing/trace_id_test.go
  samples/experimental/tracing/tracing-client.js
  samples/experimental/tracing/tracing-instrumentHTTP.js
Labels: feature, high prio

#2813 Move most capabilities out of the `core.Engine` in preparation for removal
  api/common/context.go
  api/server.go
  api/server_test.go
  api/v1/control_surface.go
  api/v1/group_routes.go
  api/v1/group_routes_test.go
  api/v1/metric_routes.go
  api/v1/metric_routes_test.go
  api/v1/routes.go
  api/v1/routes_test.go
  api/v1/setup_teardown_routes.go
  api/v1/setup_teardown_routes_test.go
  api/v1/status.go
  api/v1/status_jsonapi.go
  api/v1/status_routes.go
  api/v1/status_routes_test.go
  cmd/common.go
  cmd/run.go
  cmd/tests/cmd_run_test.go
  core/engine.go
  core/engine_test.go
  execution/scheduler.go
  lib/options_test.go
  metrics/engine/engine.go
  output/types.go
Labels: refactor
