Repository grafana/k6, pull requests merged in 2024-07, with the labels that each got.

#3819 Updates to latest browser
  go.mod
  go.sum
  vendor/github.com/grafana/xk6-browser/browser/browser_mapping.go
  vendor/github.com/grafana/xk6-browser/browser/sync_browser_mapping.go
  vendor/github.com/grafana/xk6-browser/common/browser.go
  vendor/github.com/grafana/xk6-browser/common/browser_context.go
  vendor/github.com/grafana/xk6-browser/common/helpers.go
  vendor/modules.txt
Labels: area: browser

#3824 Update to xk6-websockets@v0.6.0
  go.mod
  go.sum
  vendor/github.com/grafana/xk6-websockets/websockets/blob.go
  vendor/github.com/grafana/xk6-websockets/websockets/helpers.go
  vendor/github.com/grafana/xk6-websockets/websockets/websockets.go
  vendor/modules.txt
Labels: breaking change, documentation-needed

#3833 Update Sobek to version with ESM support
  go.mod
  go.sum
  js/bundle_test.go
  vendor/github.com/grafana/sobek/.tc39_test262_checkout.sh
  vendor/github.com/grafana/sobek/README.md
  vendor/github.com/grafana/sobek/ast/node.go
  vendor/github.com/grafana/sobek/builtin_object.go
  vendor/github.com/grafana/sobek/builtin_string.go
  vendor/github.com/grafana/sobek/compiler.go
  vendor/github.com/grafana/sobek/compiler_expr.go
  vendor/github.com/grafana/sobek/compiler_stmt.go
  vendor/github.com/grafana/sobek/modules.go
  vendor/github.com/grafana/sobek/modules_namespace.go
  vendor/github.com/grafana/sobek/modules_sourcetext.go
  vendor/github.com/grafana/sobek/object.go
  vendor/github.com/grafana/sobek/parser/expression.go
  vendor/github.com/grafana/sobek/parser/parser.go
  vendor/github.com/grafana/sobek/parser/scope.go
  vendor/github.com/grafana/sobek/parser/statement.go
  vendor/github.com/grafana/sobek/runtime.go
  vendor/github.com/grafana/sobek/token/token_const.go
  vendor/github.com/grafana/sobek/value.go
  vendor/github.com/grafana/sobek/vm.go
  vendor/modules.txt
Labels: dependencies

#3837 Update k6/experimental/timers warning and consolidate with browsers
  js/jsmodules.go
Labels: maintenance, breaking change

#3839 Update sobek
  go.mod
  go.sum
  vendor/github.com/grafana/sobek/README.md
  vendor/github.com/grafana/sobek/compiler.go
  vendor/github.com/grafana/sobek/vm.go
  vendor/modules.txt
Labels: dependencies

#3844 Update google.golang.org/grpc v1.64.0 => v1.64.1 - security fix
  go.mod
  go.sum
  vendor/google.golang.org/grpc/metadata/metadata.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: dependencies

#3845 log/file: drain lines channel after context is cancelled
  log/file.go
Labels: bug

#3848 Update StatsD output deprecation (define removal version)
  cmd/outputs.go
Labels: documentation-needed

#3746 Fix metrics for GRPC streams do not correctly include tags when stream ends
  js/modules/k6/grpc/stream.go
  js/modules/k6/grpc/stream_test.go
Labels: awaiting user, area: grpc

#3854 Deprecate k6/experimental/tracing
  js/jsmodules.go
Labels: breaking change

#3869 js: Support indirect exports for main module functions
  js/bundle.go
  js/module_loading_test.go
Labels: js-compat

#3866 Remove magic resolving of cdnjs and github "URLs"
  lib/old_archive_test.go
  loader/cdnjs.go
  loader/cdnjs_test.go
  loader/github.go
  loader/github_test.go
  loader/loader.go
Labels: breaking change

#3870 Fix tls min version in tests with go 1.22
  js/modules/k6/http/request_test.go
Labels: tests

#3813 Move cloud run and login functionalities under cloud subcommands
  cmd/cloud.go
  cmd/cloud_login.go
  cmd/cloud_run.go
  cmd/login.go
  cmd/login_cloud.go
  cmd/tests/cmd_cloud_run_test.go
  cmd/tests/cmd_cloud_test.go
Labels: enhancement
