Repository grafana/k6, pull requests merged in 2024-06, with the labels that each got.

#3767 Update deps of examples/grpc_server
  examples/grpc_server/go.mod
  examples/grpc_server/go.sum
Labels: dependencies

#3777 Stop catching panics
  cmd/panic_integration_test.go
  cmd/root_test.go
  js/bundle.go
  js/common/util.go
  js/runner.go
  js/runner_test.go
Labels: breaking change

#3779 Fixes `undefined` handler passing to the gRPC stream
  js/modules/k6/grpc/stream.go
  js/modules/k6/grpc/stream_test.go
Labels: area: grpc

#3793 Graduate to `k6/browser` from an experimental module
  cmd/tests/cmd_run_test.go
  examples/experimental/browser.js
  js/jsmodules.go
Labels: area: browser

#3795 Update sobek and goja respectfully
  go.mod
  go.sum
  vendor/github.com/dop251/goja/object_goreflect.go
  vendor/github.com/dop251/goja/runtime.go
  vendor/modules.txt
Labels: dependencies

#3797 cmd/archive: output archive to stdout if - is passed as --archive-out
  cmd/archive.go
  cmd/archive_test.go
Labels: breaking change, documentation-needed

#3810 Bump k6 version to v0.52.0
  lib/consts/consts.go
Labels: release
