Repository grafana/k6, pull requests merged in 2024-10, with the labels that each got.

#3849 Removes statsd output
  cmd/outputs.go
  go.mod
  go.sum
  output/statsd/config.go
  output/statsd/helper_test.go
  output/statsd/output.go
  output/statsd/output_test.go
  vendor/github.com/DataDog/datadog-go/LICENSE.txt
  vendor/github.com/DataDog/datadog-go/statsd/README.md
  vendor/github.com/DataDog/datadog-go/statsd/statsd.go
  vendor/github.com/DataDog/datadog-go/statsd/udp.go
  vendor/github.com/DataDog/datadog-go/statsd/uds.go
  vendor/modules.txt
Labels: breaking change, documentation-needed, dependencies, metrics-output

#3989 dependabot: add a bunch more dependencies to it
  .github/dependabot.yml
Labels: dependencies

#4000 test: split error message check to fix it for go 1.24
  js/compiler/compiler_test.go
Labels: tests

#3988 refactor: use context.AfterFunc around VU management
  js/runner.go
  lib/testutils/minirunner/minirunner.go
Labels: refactor

#4009 Update Sobek and fix http.File to not use []byte
  go.mod
  go.sum
  js/modules/k6/http/file.go
  js/modules/k6/http/file_test.go
  js/modules/k6/http/request.go
  vendor/github.com/grafana/sobek/modules_sourcetext.go
  vendor/github.com/grafana/sobek/object_goreflect.go
  vendor/github.com/grafana/sobek/parser/expression.go
  vendor/modules.txt
Labels: breaking change, dependencies

#4017 Update sobek to fix interrupt with async code
  go.mod
  go.sum
  js/modules/cjsmodule.go
  js/modules/gomodule.go
  js/modules/gomodule_basic.go
  js/modules/k6/experimental/fs/module.go
  js/modules/k6/experimental/streams/goja.go
  js/modules/k6/experimental/streams/readable_stream_default_reader.go
  js/modules/k6/experimental/streams/readable_stream_reader.go
  js/modules/k6/experimental/streams/readable_streams.go
  js/modules/k6/grpc/client.go
  js/modules/k6/http/request.go
  js/promises/promises.go
  vendor/github.com/grafana/sobek/builtin_promise.go
  vendor/github.com/grafana/sobek/modules.go
  vendor/github.com/grafana/sobek/modules_sourcetext.go
  vendor/modules.txt
Labels: high prio

#4021 dependabot: update configuration with fixes
  .github/dependabot.yml
Labels: dependencies

#4022 Replace strings.SplitN(2) with strings.Cut
  cmd/outputs.go
  cmd/tests/cmd_run_test.go
  lib/execution_segment.go
  lib/models.go
  lib/trace/otel.go
  lib/types/dns.go
  lib/types/ipblock.go
  loader/loader.go
  log/file.go
  log/loki.go
  metrics/engine/engine.go
  metrics/metric.go
  metrics/thresholds_parser.go
  output/csv/config.go
  output/influxdb/util.go
Labels: maintenance
