Repository grafana/k6, pull requests merged in 2024-08, with the labels that each got.

#3886 Drop support for log in with email & password in the new `k6 cloud login`
  cmd/cloud_login.go
Labels: cloud

#3891 Update sobek to fix usage of class if it is exported as default
  go.mod
  go.sum
  vendor/github.com/grafana/sobek/compiler.go
  vendor/github.com/grafana/sobek/compiler_stmt.go
  vendor/github.com/grafana/sobek/modules_sourcetext.go
  vendor/modules.txt
Labels: bug

#3901 Fix cloud command not listed in k6 command's help text
  cmd/cloud.go
  cmd/root_test.go
Labels: bug

#3876 Report ThresholdsHaveFailed on Cloud runs
  cmd/cloud.go
  cmd/tests/cmd_cloud_test.go
Labels: enhancement, cloud

#3908 Drop NetTrail - emit iterations metrics in runner instead of dialer
  execution/scheduler_ext_test.go
  js/runner.go
  js/runner_test.go
  lib/netext/dialer.go
  output/cloud/insights/collect_test.go
Labels: refactor, lower prio

#3915 Switch to the go1.21, introduce toolchain to go.mod
  go.mod
  go.sum
Labels: dependencies

#3912 Upgraded google.golang.org/grpc v1.64.1 => v1.65.0
  go.mod
  go.sum
  vendor/github.com/cespare/xxhash/v2/README.md
  vendor/github.com/cespare/xxhash/v2/xxhash.go
  vendor/github.com/cespare/xxhash/v2/xxhash_asm.go
  vendor/github.com/cespare/xxhash/v2/xxhash_other.go
  vendor/github.com/cespare/xxhash/v2/xxhash_safe.go
  vendor/github.com/cespare/xxhash/v2/xxhash_unsafe.go
  vendor/google.golang.org/genproto/googleapis/api/httpbody/httpbody.pb.go
  vendor/google.golang.org/genproto/googleapis/rpc/errdetails/error_details.pb.go
  vendor/google.golang.org/genproto/googleapis/rpc/status/status.pb.go
  vendor/google.golang.org/grpc/README.md
  vendor/google.golang.org/grpc/balancer/pickfirst/pickfirst.go
  vendor/google.golang.org/grpc/balancer/roundrobin/roundrobin.go
  vendor/google.golang.org/grpc/balancer_wrapper.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/tls.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/internal/backoff/backoff.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/grpcrand/grpcrand.go
  vendor/google.golang.org/grpc/internal/grpcrand/grpcrand_go1.21.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/resolver/dns/dns_resolver.go
  vendor/google.golang.org/grpc/internal/resolver/dns/internal/internal.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/picker_wrapper.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1/reflection.pb.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1/reflection_grpc.pb.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.pb.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
  vendor/google.golang.org/grpc/resolver_wrapper.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: dependencies

#3906 Introduce k6 cloud upload to replace --upload-only
  cmd/cloud.go
  cmd/cloud_login.go
  cmd/cloud_upload.go
  cmd/tests/cmd_cloud_upload_test.go
Labels: cloud

#3913 Update latest sobek: bigInt, etc
  go.mod
  go.sum
  js/bundle_test.go
  js/modules/k6/crypto/x509/x509_test.go
  js/tc39/breaking_test_errors-experimental_enhanced.json
  js/tc39/breaking_test_errors-extended.json
  js/tc39/checkout.sh
  js/tc39/tc39_test.go
  vendor/github.com/grafana/sobek/.tc39_test262_checkout.sh
  vendor/github.com/grafana/sobek/builtin_bigint.go
  vendor/github.com/grafana/sobek/builtin_global.go
  vendor/github.com/grafana/sobek/builtin_json.go
  vendor/github.com/grafana/sobek/builtin_regexp.go
  vendor/github.com/grafana/sobek/builtin_string.go
  vendor/github.com/grafana/sobek/builtin_typedarrays.go
  vendor/github.com/grafana/sobek/compiler_expr.go
  vendor/github.com/grafana/sobek/date_parser.go
  vendor/github.com/grafana/sobek/parser/lexer.go
  vendor/github.com/grafana/sobek/runtime.go
  vendor/github.com/grafana/sobek/string.go
  vendor/github.com/grafana/sobek/string_ascii.go
  vendor/github.com/grafana/sobek/typedarrays.go
  vendor/github.com/grafana/sobek/value.go
  vendor/github.com/grafana/sobek/vm.go
  vendor/modules.txt
Labels: breaking change, dependencies

#3922 Remove custom 'min' function (prior to Go v1.21)
  cmd/tests/cmd_run_test.go
  cmd/ui.go
  js/modules/k6/experimental/fs/file.go
  lib/util.go
  lib/util_test.go
  output/cloud/expv2/flush.go
Labels: breaking change

#3877 Add `discardResponseMessage` option for gRPC stream
  js/modules/k6/grpc/stream.go
  js/modules/k6/grpc/stream_test.go
  lib/netext/grpcext/conn.go
  lib/netext/grpcext/stream.go
Labels: documentation-needed, area: grpc

#3926 Document maintanance of tc39
  js/tc39/README.md
Labels: docs
