Repository grafana/k6, pull requests merged in 2024-11, with the labels that each got.

#4037 update recommendation for async check
  js/modules/k6/k6.go
Labels: ux

#4043 Adjusts recommendations for check
  js/modules/k6/k6.go
Labels: ux, lower prio

#3855 Drop `k6/experimental/tracing`
  cmd/tests/tracing_module_test.go
  examples/experimental/tracing/tracing-client.js
  examples/experimental/tracing/tracing-instrumentHTTP.js
  examples/experimental/tracing/tracing-sampling.js
  js/jsmodules.go
  js/modules/k6/experimental/tracing/client.go
  js/modules/k6/experimental/tracing/client_test.go
  js/modules/k6/experimental/tracing/encoding.go
  js/modules/k6/experimental/tracing/module.go
  js/modules/k6/experimental/tracing/module_test.go
  js/modules/k6/experimental/tracing/options.go
  js/modules/k6/experimental/tracing/options_test.go
  js/modules/k6/experimental/tracing/propagator.go
  js/modules/k6/experimental/tracing/propagator_test.go
  js/modules/k6/experimental/tracing/sampling.go
  js/modules/k6/experimental/tracing/trace_id.go
  js/modules/k6/experimental/tracing/trace_id_test.go
Labels: breaking change

#4033 V0.55.0 Release Notes
  release notes/v0.55.0.md
Labels: release

#4055 Update release template following v0.55.0
  .github/ISSUE_TEMPLATE/release.md
Labels: enhancement

#4072 Use the precompiled 'gotip' on the xk6 workflow
  .github/workflows/xk6.yml
Labels: ci

#4076 js/modules: update docs around NewModuleInstance
  js/modules/modules.go
Labels: docs
