Repository grafana/k6, pull requests merged in 2024-02, with the labels that each got.

#3555 Use pre-compiled Go tip
  .github/workflows/test.yml
Labels: ci

#3586 fix zip-slip noise in tests
  lib/testutils/untar.go
Labels: lower prio

#3587 Stabilize k6/experimental/timers into k6/timers
  cmd/tests/eventloop_test.go
  examples/experimental/ws.js
  examples/timers.js
  go.mod
  go.sum
  js/jsmodules.go
  js/modules/k6/timers/timers.go
  js/modules/k6/timers/timers_test.go
  vendor/github.com/grafana/xk6-timers/LICENSE
  vendor/modules.txt
Labels: documentation-needed

#3588 Update codeql to v3
  .github/workflows/codeql-analysis.yml
Labels: lower prio, ci

#3590 Bump Go module version to 1.20
  go.mod
Labels: maintenance

#3593 Fix ramping-arrival-rate execution requirements
  lib/executor/ramping_arrival_rate.go
  lib/executor/ramping_arrival_rate_test.go
Labels: bug, executors

#3595 Fix auto assign on issue comment
  .github/workflows/issue-auto-assign.yml
Labels: ci

#3617 Update golang.org/x/net to fix a cve-2019-9514
  go.mod
  go.sum
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/env_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: dependencies
