Repository grafana/k6, pull requests merged in 2024-09, with the labels that each got.

#3938 Update go workflows to 1.23
  .github/actions/lint/action.yml
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/tc39.yml
  .github/workflows/test.yml
  .github/workflows/wpt.yml
  .github/workflows/xk6.yml
Labels: ci

#3930 Perform token validation as part of 'k6 cloud login'
  cloudapi/api.go
  cmd/cloud_login.go
Labels: cloud

#3935 js: DRY creation of a runner from archive in the tests
  js/console_test.go
  js/module_loading_test.go
  js/runner_test.go
  js/share_test.go
Labels: refactor

#3838 Drop experimental timers
  js/jsmodules.go
Labels: breaking change, documentation-needed

#3743 Add an experimental csv module exposing a streaming csv parser
  examples/experimental/csv-parse.js
  examples/experimental/csv-parser.js
  examples/experimental/data.csv
  js/jsmodules.go
  js/modules/k6/data/data.go
  js/modules/k6/data/share.go
  js/modules/k6/experimental/csv/module.go
  js/modules/k6/experimental/csv/module_test.go
  js/modules/k6/experimental/csv/reader.go
  js/modules/k6/experimental/csv/reader_test.go
  js/modules/k6/experimental/fs/file.go
  js/modules/k6/experimental/fs/file_test.go
  js/modules/k6/experimental/fs/module.go
  js/modules/k6/experimental/fs/module_test.go
Labels: feature, documentation-needed

#3947 Prevent panic when 'options' value is nil
  js/bundle.go
  js/bundle_test.go
Labels: bug

#3801 Add a second argument to callbacks for grpc streams with metadata
  js/modules/k6/grpc/listeners.go
  js/modules/k6/grpc/stream.go
  js/modules/k6/grpc/stream_test.go
Labels: documentation-needed, area: grpc

#3931 [2/2] Make k6 cloud run --local-execution upload test archive
  cloudapi/api.go
  cloudapi/api_test.go
  cmd/cloud_run.go
  cmd/config.go
  cmd/outputs.go
  cmd/tests/cmd_cloud_run_test.go
  output/cloud/output.go
  output/types.go
Labels: enhancement

#3965 Update to k6 browser 1.8.3
  go.mod
  go.sum
  vendor/github.com/grafana/xk6-browser/common/page.go
  vendor/modules.txt
Labels: dependencies

#3966 Update to 1.8.4 of the browser moduler
  go.mod
  go.sum
  vendor/github.com/grafana/xk6-browser/common/element_handle.go
  vendor/modules.txt
Labels: dependencies

#3972 Update xk6-websockets to fix readyState bug
  go.mod
  go.sum
  vendor/github.com/grafana/xk6-websockets/websockets/websockets.go
  vendor/modules.txt
Labels: dependencies
