Repository grafana/k6, pull requests merged in 2024-04, with the labels that each got.

#3671 Deprecate magic resolving of cdnjs and github "URLs"
  loader/loader.go
Labels: breaking change

#3672 Update 'envconfig' to fix environment variables reads
  cmd/config_consolidation_test.go
  go.mod
  go.sum
  vendor/github.com/mstoykov/envconfig/envconfig.go
  vendor/modules.txt
Labels: bug

#3627 cloudapi: lint fixes + just use crypto/rand
  cloudapi/client.go
  cloudapi/config.go
  cloudapi/config_test.go
Labels: lower prio, maintenance

#3530 Completely remove experimental GRPC module
  js/jsmodules.go
  js/modules/k6/grpc/grpc.go
Labels: maintenance, breaking change, documentation-needed, area: grpc

#3678 js/path_resolution_test: more ESM related tests
  js/path_resolution_test.go
Labels: tests

#3684 Remove no longer needed CI job (Homebrew)
  .github/workflows/build.yml
Labels: ci

#3695 ci: temporary disable running tests on macOS
  .github/workflows/test.yml
Labels: tests, ci

#3680 Lock module resolution after initialization
  js/bundle.go
  js/modules/resolution.go
  js/runner_test.go
Labels: breaking change

#3681 Emit warning if require will not comply with specification
  js/modules/require_impl.go
  js/path_resolution_test.go
Labels: breaking change

#3717 fix line numbers when inline sourcemap is used
  js/compiler/compiler.go
  js/initcontext_test.go
Labels: bug

#3696 Add ReadableStream support to k6
  .github/workflows/wpt.yml
  .gitignore
  examples/experimental/streams.js
  js/jsmodules.go
  js/modules/k6/experimental/streams/errors.go
  js/modules/k6/experimental/streams/errors_gen.go
  js/modules/k6/experimental/streams/goja.go
  js/modules/k6/experimental/streams/module.go
  js/modules/k6/experimental/streams/queue.go
  js/modules/k6/experimental/streams/readable_stream_controller.go
  js/modules/k6/experimental/streams/readable_stream_default_controller.go
  js/modules/k6/experimental/streams/readable_stream_default_reader.go
  js/modules/k6/experimental/streams/readable_stream_reader.go
  js/modules/k6/experimental/streams/readable_streams.go
  js/modules/k6/experimental/streams/readable_streams_test.go
  js/modules/k6/experimental/streams/tests/README.md
  js/modules/k6/experimental/streams/tests/checkout.sh
  js/modules/k6/experimental/streams/tests/reentrant-strategies.any.js.patch
  js/modules/k6/experimental/streams/tests/rs-test-templates.js.patch
  js/modules/k6/experimental/streams/tests/testharness.js.patch
  js/modules/k6/experimental/streams/underlying_source.go
  js/modulestest/compile.go
  js/modulestest/runtime.go
Labels: feature, documentation-needed

#3723 Release notes: Browser async `Tap`
  release notes/v0.51.0.md
Labels: docs, area: browser

#3725 Increase golang ci lint timeout
  .golangci.yml
Labels: ci
