Repository grafana/k6, pull requests merged in 2024-05, with the labels that each got.

#3752 feat: upgrade xk6-dashboard to v0.7.3
  go.mod
  go.sum
  vendor/github.com/grafana/xk6-dashboard/dashboard/aggregate.go
  vendor/github.com/grafana/xk6-dashboard/dashboard/assets/packages/report/dist/index.html
  vendor/github.com/grafana/xk6-dashboard/dashboard/assets/packages/ui/dist/assets/index-4796c824.js
  vendor/github.com/grafana/xk6-dashboard/dashboard/assets/packages/ui/dist/assets/index-8105e2d0.css
  vendor/github.com/grafana/xk6-dashboard/dashboard/assets/packages/ui/dist/assets/index-beb72b0a.js
  vendor/github.com/grafana/xk6-dashboard/dashboard/assets/packages/ui/dist/assets/index-fa41f432.css
  vendor/github.com/grafana/xk6-dashboard/dashboard/assets/packages/ui/dist/assets/rewind_time-def68db1.svg
  vendor/github.com/grafana/xk6-dashboard/dashboard/assets/packages/ui/dist/index.html
  vendor/github.com/grafana/xk6-dashboard/dashboard/builtin.go
  vendor/github.com/grafana/xk6-dashboard/dashboard/command.go
  vendor/github.com/grafana/xk6-dashboard/dashboard/extension.go
  vendor/github.com/grafana/xk6-dashboard/dashboard/meter.go
  vendor/github.com/grafana/xk6-dashboard/dashboard/registry.go
  vendor/github.com/grafana/xk6-dashboard/dashboard/replay.go
  vendor/github.com/grafana/xk6-dashboard/dashboard/report.go
  vendor/github.com/grafana/xk6-dashboard/dashboard/testdata/result.ndjson
  vendor/github.com/grafana/xk6-dashboard/dashboard/testdata/result.ndjson.gz
  vendor/github.com/grafana/xk6-dashboard/dashboard/web.go
  vendor/modules.txt
Labels: breaking change, dependencies

#3750 Refactor group and check to not be tightly coupled
  api/v1/group_routes.go
  api/v1/group_routes_test.go
  cmd/run.go
  cmd/test_load.go
  cmd/ui.go
  js/initcontext_test.go
  js/modules/k6/grpc/params_test.go
  js/modules/k6/grpc/teststate_test.go
  js/modules/k6/http/request_test.go
  js/modules/k6/http/response_test.go
  js/modules/k6/k6.go
  js/modules/k6/k6_test.go
  js/modules/k6/ws/ws_test.go
  js/runner.go
  js/runner_test.go
  lib/models.go
  lib/runner.go
  lib/test_state.go
  lib/testutils/minirunner/minirunner.go
  lib/vu_state.go
Labels: refactor, breaking change

#3760 Fix race condition in ramping-vus tests
  lib/executor/ramping_vus_test.go
Labels: tests
