Repository grafana/k6, pull requests merged in 2024-01, with the labels that each got.

#3520 Stop using deprecated net.Dialer.DualStack
  js/initcontext_test.go
  js/runner.go
  lib/netext/httpext/error_codes_test.go
  lib/netext/httpext/tracer.go
  lib/testutils/httpmultibin/httpmultibin.go
Labels: maintenance

#3525 Collect usage about used js modules and outputs
  cmd/builtin_output_gen.go
  cmd/outputs.go
  cmd/outputs_test.go
  cmd/report.go
  cmd/report_test.go
  cmd/run.go
  cmd/test_load.go
  js/modules/resolution.go
Labels: documentation-needed

#3526 js: path based tests refactor
  js/path_resolution_test.go
Labels: tests

#3519 feat: enabling the extraction of a specific selection from an element
  js/modules/k6/html/element.go
  js/modules/k6/html/element_test.go
Labels: documentation-needed

#3538 Fix browser not found err in TestBrowserPermissions
  cmd/tests/cmd_run_test.go
Labels: tests, area: browser

#3574 Update the release issue with some info on definitely typed version
  .github/ISSUE_TEMPLATE/release.md
Labels: maintenance

#3554 Remove flaky gRPC tests
  js/modules/k6/grpc/client_test.go
Labels: tests, area: grpc

#3573 Bump to github actions to use node 20
  .github/actions/lint/action.yml
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/issue-auto-assign.yml
  .github/workflows/lint.yml
  .github/workflows/packager.yml
  .github/workflows/tc39.yml
  .github/workflows/test.yml
  .github/workflows/xk6.yml
Labels: ci
