Repository grafana/k6, pull requests merged in 2024-12, with the labels that each got.

#4093 Introduces --json flag for k6 version sub-command
  cmd/root.go
  cmd/version.go
  cmd/version_test.go
  lib/consts/consts.go
Labels: ux, breaking change

#4143 Fix k6packager workflow
  .github/workflows/packager.yml
Labels: ci

#4092 Populate __ENV.K6_CLOUDRUN_TEST_RUN_ID on local executions of k6 cloud run
  cloudapi/config.go
  cmd/cloud_run.go
  cmd/outputs_cloud.go
  cmd/tests/cmd_cloud_run_test.go
  lib/options.go
  output/cloud/output.go
Labels: cloud
