Repository grafana/k6, pull requests merged in 2025-03, with the labels that each got.

#4089 Revamp the end-of-test summary
  .github/workflows/xk6-tests/xk6-test.js
  internal/cmd/builtin_output_gen.go
  internal/cmd/outputs.go
  internal/cmd/outputs_test.go
  internal/cmd/run.go
  internal/cmd/run_test.go
  internal/cmd/runtime_options.go
  internal/cmd/runtime_options_test.go
  internal/cmd/testdata/summary/api.js
  internal/cmd/testdata/summary/browser.js
  internal/cmd/testdata/summary/grpc.js
  internal/cmd/testdata/summary/main.js
  internal/cmd/testdata/summary/ws.js
  internal/cmd/tests/cmd_run_grpc_test.go
  internal/cmd/tests/cmd_run_test.go
  internal/cmd/ui.go
  internal/js/runner.go
  internal/js/summary-legacy.js
  internal/js/summary-wrapper.js
  internal/js/summary.go
  internal/js/summary.js
  internal/js/summary_test.go
  internal/lib/summary/doc.go
  internal/lib/summary/summary.go
  internal/lib/testutils/minirunner/minirunner.go
  internal/output/summary/data.go
  internal/output/summary/doc.go
  internal/output/summary/summary.go
  internal/output/summary/summary_test.go
  lib/models.go
  lib/runner.go
  lib/runtime_options.go
  lib/summary.go
  metrics/sink.go
Labels: breaking change

#4602 UX: better error message for json errors while parsing options
  internal/js/bundle.go
  internal/js/bundle_test.go
Labels: ux

#4618 Local templates support in `k6 new`
  internal/cmd/new.go
  internal/cmd/new_test.go
  internal/cmd/templates/templates.go
Labels: feature, documentation-needed

#4630 browser: fix web vitals test flakiness on Windows
  internal/js/modules/k6/browser/tests/webvital_test.go
Labels: tests
