Repository grafana/k6, pull requests merged in 2025-02, with the labels that each got.

#4522 browser: reduce races in evaluate*
  internal/js/modules/k6/browser/browser/page_mapping.go
Labels: area: browser

#4532 Clone Bundle's URLs into lib.Archive
  internal/js/bundle.go
Labels: bug, cloud

#4529 Fix E2E browser CI flakiness by reducing example number of browser
  examples/browser/multiple-scenario.js
Labels: ci

#4509 Bump k6 version
  lib/consts/consts.go
Labels: maintenance

#4511 Release v0.57.0
  release notes/v0.57.0.md
Labels: release

#4547 Add true color detection for k6 banner
  internal/cmd/root.go
  internal/cmd/ui.go
Labels: ux

#4546 Try to make TestConstantArrivalRateRunCorrectRate less flaky
  lib/executor/constant_arrival_rate_test.go
Labels: tests

#4539 browser: get session only once - trying to fix #4125
  internal/js/modules/k6/browser/common/frame_session.go
Labels: area: browser

#4541 Support comma in tag values through cli flag
  internal/cmd/options.go
  internal/cmd/tests/cmd_run_test.go
Labels: ux, breaking change

#4551 Add doc updates checklist to PR template
  .github/pull_request_template.md
Labels: docs

#4561 Update sobek - a fix for Function.apply
  go.mod
  go.sum
  vendor/github.com/grafana/sobek/README.md
  vendor/github.com/grafana/sobek/builtin_function.go
  vendor/github.com/grafana/sobek/runtime.go
  vendor/modules.txt
Labels: dependencies

#4576 browser: Add page on request example
  examples/browser/pageon-request.js
Labels: docs, area: browser
