Repository grafana/k6, pull requests merged in 2025-01, with the labels that each got.

#4164 Improve release notes template
  .github/ISSUE_TEMPLATE/release.md
Labels: docs

#4172 Drop slack URL
  README.md
Labels: docs, lower prio

#4173 Update the grpc_server_example
  examples/grpc_server/go.mod
  examples/grpc_server/go.sum
Labels: lower prio

#4184 Fix some browser Windows tests
  js/modules/k6/browser/tests/browser_context_test.go
  js/modules/k6/browser/tests/page_test.go
  js/modules/k6/browser/tests/test_browser.go
Labels: bug, tests, area: browser

#4190 Minor clean up
  Dependencies.md
  modtools_frozen.yml
  vendor.linter.txt
Labels: lower prio

#4176 Warn on shorthand options overriding scenarios
  cmd/config.go
  cmd/config_consolidation_test.go
Labels: ux

#4294 TestStreamLogsToLogger: increase wait time to get less flakiness
  cloudapi/logs_test.go
Labels: tests
