Repository grafana/k6, pull requests merged in 2025-08, with the labels that each got.

#4990 chore: Fix race in timers test due to context reset
  internal/js/tc55/timers/timers_test.go
Labels: tests, ci

#4974 ci: Run tests with `-race` always
  .github/workflows/test.yml
Labels: ci

#4961 Browser: add route.fulfill
  internal/js/modules/k6/browser/browser/page_mapping.go
  internal/js/modules/k6/browser/browser/route_mapping.go
  internal/js/modules/k6/browser/common/frame_manager.go
  internal/js/modules/k6/browser/common/http.go
  internal/js/modules/k6/browser/common/network_manager.go
  internal/js/modules/k6/browser/tests/frame_manager_test.go
Labels: enhancement, area: browser, browser: playwright

#4971 Browser: add route.continue
  examples/browser/route_continue.js
  internal/js/modules/k6/browser/browser/route_mapping.go
  internal/js/modules/k6/browser/common/frame_manager.go
  internal/js/modules/k6/browser/common/http.go
  internal/js/modules/k6/browser/common/network_manager.go
  internal/js/modules/k6/browser/tests/frame_manager_test.go
Labels: area: browser, browser: playwright

#5007 ci: Again run windows tests with -race and MacOs cleanup
  .github/workflows/test.yml
Labels: ci

#5057 fix: do not panic on `k6 login cloud`
  internal/cmd/launcher.go
  internal/cmd/tests/tests_test.go
Labels: bug

#5089 grpc: Fix usage of Any types after refactor on protobuf loading
  internal/js/modules/k6/grpc/client.go
  internal/js/modules/k6/grpc/client_test.go
  internal/lib/netext/grpcext/conn.go
  internal/lib/netext/grpcext/stream.go
Labels: high prio, area: grpc
