Repository grafana/k6, pull requests merged in 2025-04, with the labels that each got.

#4675 Move CSV output to internal as preparations for v1.0.0
  internal/cmd/outputs.go
  internal/output/csv/config.go
  internal/output/csv/config_test.go
  internal/output/csv/doc.go
  internal/output/csv/output.go
  internal/output/csv/output_test.go
  internal/output/csv/time_format_gen.go
Labels: breaking change

#4676 Move k6 js module to internal as preparations for v1.0.0
  internal/js/jsmodules.go
  internal/js/modules/k6/k6.go
  internal/js/modules/k6/k6_test.go
  internal/js/modules/k6/marshalling_test.go
  internal/js/runner_test.go
Labels: breaking change

#4678 Move consts package to internal as preparations for v1.0.0
  internal/js/bundle.go
  internal/js/bundle_test.go
  internal/js/initcontext_test.go
  internal/js/runner.go
  internal/js/timeout_error.go
  internal/js/timeout_error_test.go
  internal/lib/consts/js.go
  lib/executor/base_config.go
Labels: breaking change

#4672 Add `execution.test.fail` to fail a test, and let it finish
  cmd/state/state.go
  errext/exitcodes/codes.go
  errext/interrupt_error.go
  internal/cmd/run.go
  internal/cmd/run_test.go
  internal/cmd/test_load.go
  internal/cmd/testdata/fail.js
  internal/cmd/tests/test_state.go
  internal/js/modules/k6/execution/execution.go
  internal/js/modules/k6/execution/execution_test.go
  internal/js/runner.go
  lib/test_state.go
  lib/vu_state.go
Labels: enhancement

#4698 Summary: Display thresholds values even when not in summaryTrendStats
  internal/cmd/tests/cmd_run_test.go
  internal/js/summary.js
  internal/output/summary/data.go
  internal/output/summary/data_test.go
Labels: bug, ux

#4739 Fix deprecated `GetLayoutMetrics.VisualViewport`
  internal/js/modules/k6/browser/common/screenshotter.go
Labels: maintenance

#4749 Update GHA to fix zizmor warnings
  .github/actions/lint/action.yml
  .github/workflows/browser_e2e.yml
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yml
  .github/workflows/packager.yml
  .github/workflows/tc39.yml
  .github/workflows/test.yml
  .github/workflows/trivy.yml
  .github/workflows/wpt.yml
  .github/workflows/xk6.yml
Labels: high prio
